# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: public

jobs:
# Please do not rename this job
  build-project:
    name: build portfolio_aa
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      - name: Build Node assets
        env:
          API_KEY: 6ab17453-c041-48a6-9ec9-ac6e04a5b1a1
          CI: true
          NEXT_PUBLIC_APP_ID: 907d25b7-b52e-4090-85d0-44e0221b15e4
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm install --global yarn
          yarn install --frozen-lockfile
          yarn build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: 709914ee-b54e-4359-b9e0-fd292934276e
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/portfolio_aa/config.yaml
          action: upload
